# Generated by Django 2.0.4 on 2018-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='tipo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='em_grupo',
            field=models.BooleanField(default=False),
        ),
    ]
