# Generated by Django 2.0.4 on 2018-05-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20180521_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('masc', 'masculino'), ('fem', 'feminino'), ('open', 'não declarado')], default='open', max_length=20)),
                ('senha', models.CharField(max_length=50)),
                ('professor', models.BooleanField(default=False)),
            ],
        ),
    ]
