# Generated by Django 2.0.4 on 2018-05-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='em_grupo',
            new_name='em_equipe',
        ),
    ]
