# Generated by Django 2.0.4 on 2018-05-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_auto_20180522_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trofeu',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('pontuacao', models.IntegerField(primary_key=True, serialize=False)),
                ('icone', models.ImageField(upload_to='trofeus/<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='trofeu',
        ),
        migrations.AddField(
            model_name='atividade',
            name='trofeu1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trofeu1', to='atividades.Trofeu'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trofeu2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trofeu2', to='atividades.Trofeu'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trofeu3',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trofeu3', to='atividades.Trofeu'),
        ),
    ]
