# Generated by Django 2.0.4 on 2018-05-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_auto_20180527_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='trofeu2',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='trofeu3',
        ),
    ]
