# Generated by Django 2.0.4 on 2018-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0006_auto_20180527_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trofeu',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='trofeus/<django.db.models.fields.CharField>'),
        ),
    ]
