# Generated by Django 2.0.4 on 2018-05-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_atividade_trofeu2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='trofeu2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trofeu2', to='atividades.Trofeu'),
        ),
    ]
