# Generated by Django 2.0.4 on 2018-05-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_auto_20180527_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='trofeu3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trofeu3', to='atividades.Trofeu'),
        ),
    ]
